### ISSUE TITLE
[Bug]: New "UseNewTextureAllocator" setting breaks anti-aliasing in AMD card.

### ISSUE THREAD

**Issue by Telmator** [emoose/OutRun2006Tweaks#105]
### Tweaks version

outrun2006tweaks-1a4c22b4f8c6c5684c07a49fccc3d646a0889441

![UseNewTextureAllocator_false](https://github.com/user-attachments/assets/a1243be8-b3f2-4cb5-a0f3-d8dc1eddfd5b)
![UseNewTextureAllocator_true](https://github.com/user-attachments/assets/bcbd8f8a-fec8-4419-be57-399c81e18e07)
[OutRun2006Tweaks.log](https://github.com/user-attachments/files/16489195/OutRun2006Tweaks.log)
The new UseNewTextureAllocator setting set as "true" is breaking anti-aliasing in my AMD card, tried with several driver versions. My card is a Sapphire 6800 XT, and forcing the AA through the Adrenalin panel does not work either. Once I disable "UseNewTextureAllocator" AA is working again. 

I'm calling the antialiasing feature with DX/ANTIALIASING = 2 in the "outrun2006.ini" file.

Attaching sample screenshots.

**Comment by emoose** [comment]
Looks like it might be related to mip-mapping, the new allocator code is meant to handle that but maybe something could be broken there.

(AFAIK D3D9 is supposed to generate mip-maps when the texture itself is missing them, now I wonder if the perf/stuttering fix from the new allocator could be because it's not generating mip-maps now...)

Has anyone with non-AMD card also noticed a graphical downgrade with `UseNewTextureAllocator`?

**Comment by Tenome** [comment]
1080 TI, seems fine to me. I'm presuming the second one in OP is the incorrect one right? Though I do force extra AA through the GPU control panel.

![image](https://github.com/user-attachments/assets/4aa92f9a-57f5-4424-995d-8cf589b9bc3f)

**Comment by Telmator** [comment]
Hi @Tenome . Yes, the second one is the one where I applied UseNewTextureAllocator=true. AA is missing there, you can see that in the road marks in the distance. 
Unfortunately forcing AA via Adrenalin does not work (and I saw many posts of people complaining that it barely works in many titles).

**Comment by Telmator** [comment]
I'm getting a black screen now with the latest action (outrun2006tweaks-859fd70e1c0057180f5bb73fd66b8f96fd26c3d2.zip) if I use UseNewTextureAllocator=true. Which is weird because it worked for me initially but now after replacing textures with new ones from Github, the whole thing is broken. Even if I remove the custom textures/load files altogether. With this setting the screen is black when launching the game.

**Comment by Tenome** [comment]
I experienced the same after installing action [cf2c7ee](https://github.com/emoose/OutRun2006Tweaks/commit/cf2c7eef04d6c598a9785edb0e046aca9d44e595). Downgrading back down to 0.5 [4650516](https://github.com/emoose/OutRun2006Tweaks/commit/46505163c44926f292c09413759e373f1cf35985) fixed it, so presumably the fix for AMD minmaps messed something up regarding textures (because they don't have generated minmaps?)

![OR2006C2C_xOIWAzKpj8](https://github.com/user-attachments/assets/176595be-24a6-4b58-9af7-129a53c0362b)

**Comment by emoose** [comment]
Ah reproduced it after I disabled custom textures, seems UI is asking for 0 mips (telling D3D to gen mips as needed), so our code ends up writing 0 textures...

There's not really much point to genning mips for UI since they'll only use main mip level though, added something to force it to 1 mip in latest action.

**Comment by Tenome** [comment]
We seem to be back, thanks for the quick fix.

![image](https://github.com/user-attachments/assets/5e1d9f36-a457-4411-81ae-7c502a7fdaca)

**Comment by Telmator** [comment]
I just tested this and the black screen was returned when you had all your texture files in folders, inside "load". If you had .dds files inside "load" the black screen was gone.

**Comment by Tenome** [comment]
Sounds like it's somehow interfering with the EnableTextureCache feature, which requires the textures to be in their own folders.

**Comment by emoose** [comment]
@Telmator that's with the latest build from https://github.com/emoose/OutRun2006Tweaks/actions/runs/10335785581? Or do you mean that's how it was before?

**Comment by Telmator** [comment]
That was with the previous build, thank you. The new build works OK.
