### ISSUE TITLE
Optionally remove online-related features from main menu

### ISSUE THREAD

**Issue by lance8765** [emoose/OutRun2006Tweaks#13]
Hi again, i wonder if' it's possible to add an option to toggle online features on/off from the main menu (see screenshot, circled in green)

![340351974-664777bb-9c6d-4d89-a5be-d7e715b881d3](https://github.com/emoose/OutRun2006Tweaks/assets/159916775/a257a60e-1a5a-4c0a-a0e8-8d9a7f8c3d76)

**Comment by emoose** [comment]
I think all these options are stored in the texture files, makes it a little difficult to locate the code for them unfortunately since I can't just search for "SIGN-IN" in the code.
(since I only have debug symbols for the original Outrun 2 SP I don't really have much visibility into the C2C stuff neither, hoping some prototype version of C2C might appear some day which includes symbols with it...)

If texture swapping is added I guess the sign-in stuff could probably just be erased from the texture file to hide them, the multiplayer option might take a bit more work to remove though.

**Comment by emoose** [comment]
Ah seems that the sign-in text isn't a texture, found a way to stop game drawing those, added it in 0.3.0 as `HideOnlineSigninText`: https://github.com/emoose/OutRun2006Tweaks/releases/tag/v0.3.0

It still shows the F1 button at the bottom though, haven't found where that gets drawn yet...

**Comment by espiox** [comment]
The area where the text “Not Signed In” appears in the screenshot above is instead used to display your current OutRun Miles in the Japanese PS2 version, which seems way more useful.

**Comment by lance8765** [comment]
> The area where the text “Not Signed In” appears in the screenshot above is instead used to display your current OutRun Miles in the Japanese PS2 version, which seems way more useful.

Yeah... example here: https://www.youtube.com/watch?v=9G6grKzHhDI

**Comment by lance8765** [comment]
So... this can be considered solved, right?

And i guess #70 will not be considered anymore at this point?

Should i close both?

**Comment by emoose** [comment]
Yeah we can probably close this one, I think #70 might still be a nice idea instead of the boring "Not Signed In" text though, but the flashing above 60FPS is still an issue sadly..
