### ISSUE TITLE
Spider's shadow

### ISSUE THREAD

**Issue by RIKLAVIEGASINTRODUCTION** [emoose/OutRun2006Tweaks#23]
360 Spider's shadow tends to cull often. What's curious is that the original Xbox version of OT2 has those black sprites that the traffic & rivals have to simulate AO kind of thing in addition to the real time shadows but c2c doesn't have them. Perhaps it was originally meant to mask the culling. Idk.

https://github.com/emoose/OutRun2006Tweaks/assets/92535412/1b31b708-2bcf-4d3f-93f9-73f64cd8d182

It'd be nice if something could be done about this.

**Comment by emoose** [comment]
Should mostly be fixed with d0d4cd70f02a09af51341cb3df0e3e15a1664837 now, that restores the base shadow at least, 

Stencil shadow still has some issues though, the main one you showed gets masked by the base shadow, but I noticed sometimes end screens that have your car shown at an angle have weird stencil shadows behind it (eg. if you do one of the single gf mission levels, when you end it on the highway it almost always bugs the shadow out, I'll see if I can get a pic soon...)

Wonder if console vers also have issues with the stencil shadow too, apparently stencil shadowing can have a lot of pitfalls if they aren't implemented properly :/
