### ISSUE TITLE
Clarissa's model is censored in the arcade ending cutscene.

### ISSUE THREAD

**Issue by Tenome** [emoose/OutRun2006Tweaks#61]
So I'm not clogging up the Texture Pack thread.

`RestoreJPClarissa` turned on. Old censored model being loaded for the Heart Attack cutscene?

![OR2006C2C_vRNlDNrhKp](https://github.com/user-attachments/assets/60315b3d-0736-4424-a36f-1e463bc16e32)

**Comment by lance8765** [comment]
I wonder if it is censored while she is on the passenger seat...

**Comment by Tenome** [comment]
> I wonder if it is censored while she is on the passenger's seat during gameplay...

It didn't look like she was. The ending cutscene model might just load a different chara ID like emoose suggested.

**Comment by emoose** [comment]
Might have found the code that switches her model, model 14 / 0xE seems to be uncensored while 15 / 0xF is censored, inside `get_chrset` func is a check that changes it to 0xF if it was using 0xE.

If I remove that check her model just becomes invisible though... which is weird because if I force 0xE to load in as the passenger, that model does draw fine (though with pretty messed up anims, I'll spare you from seeing that)

Haven't found anything that would make the ending chara render different to the passenger yet, will try looking into it some more.

**Comment by emoose** [comment]
Should be fixed in https://github.com/emoose/OutRun2006Tweaks/commit/f699096aa01113c7fbca85e7840b57cea9e8cdd1

Should hopefully solve the issue mentioned above with her model being invisible/not rendering, I've only really tested one cutscene with this though, not sure if the fix will work on all of them.

**Comment by Tenome** [comment]
Now that I can compare both folders, they appear identical, except the USA archive has the texture 357EB551 in it (the censor cloth).
