### ISSUE TITLE
[Feature Request]: Tools for extracting and repacking

### ISSUE THREAD

**Issue by Sonic-TV** [emoose/OutRun2006Tweaks#75]
### Describe the feature you'd like to see added

as there're no ways to extract SZ files and repack them conveniently for custom graphics.

**Comment by Tenome** [comment]
Howard (FXT guy) has a tool called OutrunX in the forum (in the Hacking 2006 thread I think) that can unpack and repack .sz files.

**Comment by Sonic-TV** [comment]
> Howard (FXT guy) has a tool called [OutrunX in the forum](http://forum.arcadecontrols.com/index.php/topic,130891.msg1347631.html#msg1347631) that can unpack and repack .sz files.

Tried, I can't open the extracted DDS files, Visual Studio gives me this error.
File names are starting with SPR.
![image-3](https://github.com/user-attachments/assets/95766173-697b-4b22-9df2-bc5dd7ce1814)
Translation: The file format is not supported, or the file has binary characters. Opening using other editor.

**Comment by emoose** [comment]
Just noticed that Lindburgh does include a `carview` exe with it, which actually includes structures for a lot of the model formats inside 😱

Got xmt model files almost 100% parsing with 010 editor now:

![image](https://github.com/user-attachments/assets/46f5b20b-5121-4526-9555-c66a18e4f86e)

Next step would be somehow exporting this into some kind of model file...

There's also some structs around the sprites too, so hopefully can map out the weird data before the XPR0 (which should be atlas related afaik)

**Comment by Tenome** [comment]
> Just noticed that Lindburgh has a `carview` exe with it, which actually includes structures for a lot of the model formats inside 😱
> 
> Got xmt model files almost 100% parsed into 010 editor structs now:
> 
> ![image](https://private-user-images.githubusercontent.com/1755499/350686625-21379412-4071-46a0-b582-c9cf18c2c4d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1MDQ2MDEsIm5iZiI6MTcyMTUwNDMwMSwicGF0aCI6Ii8xNzU1NDk5LzM1MDY4NjYyNS0yMTM3OTQxMi00MDcxLTQ2YTAtYjU4Mi1jOWNmMThjMmM0ZDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMTkzODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjZhMDg2MDdiZDE0N2MzNzllZGU2MWE2ZmI5YjY1M2VhNWQxMDg4MDg1NzJiMDdiYjlkMzYzMmY5M2I4N2NmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.cEJtRywMAmDE8Y3d78ggc7tlz83irf7rpD6lvbXjMR4)
> 
> Next step would be somehow exporting this into some kind of model file...
> 
> There's also some structs around the sprites too, so hopefully can map out the weird data before the XPR0 (which should be atlas related afaik)

I managed to rip some models with Ninja Ripper. The car models come in multiple parts (frame, and then the wheels and bottom separately).

**Comment by emoose** [comment]
Pushed some templates for xst/xmt to https://github.com/emoose/OutRun2006Tweaks/tree/master/docs/file_formats

Haven't added a XMT template for C2C yet since it seems to have changed quite a bit to Lindbergh (becoming PMT instead?), hopefully most of the structs might end up pretty close though.

**Comment by Sonic-TV** [comment]
![image](https://github.com/user-attachments/assets/428a0966-e3aa-4200-9bb5-7c12ff1a1df6)
it finally works, thanks.
now it's time to get a script and do a full dump of the PC and xbox sprites.

**Comment by emoose** [comment]
Put a tool together which can let you extract the XSTs and convert the atlas rectangles (start x/y, end x/y) to XML, and also repack modified XML back into XST / SZ, maybe can help fix some of the texture cutoffs with it.
[OutRun2Tool-0.1.zip](https://github.com/user-attachments/files/16345300/OutRun2Tool-0.1.zip)

Example output:
[spr_sprani_adv_cvt_xst-unpacked.zip](https://github.com/user-attachments/files/16345382/spr_sprani_adv_cvt_xst-unpacked.zip)

```
Usage:
 OR2Tool.exe [-xml XmlPath] [-o OutputPath] InputPath

If -xml isn't specified, the input file will be unpacked to specified OutputPath
 or to the InputPath without .sz extension

If -xml is specified, the XML will be applied onto the input file
 and the updated file will either be written to OutputPath, or [InputPath]_new.sz
```

There isn't any support for replacing the actual textures yet, really it's probably better to use tweaks for texture replacement so it can also scale all the atlas coordinates up for you, otherwise you'd have to increase them all manually.

The way the XML stuff works is by applying a changed XML onto an existing _xst.sz file, it can't create a whole new _xst.sz yet so you have to give it the path to an existing one.

Here's a small walkthru how it can be used:

1. Drag & drop a xst.sz onto Outrun2Tool.exe -> will unpack the xst to a subfolder next to the XST you dropped
2. Edit the info.xml that was extracted, adjust atlas stuff
3. Open command-prompt, and let the tool know the xml path & input file:
`Outrun2Tool -xml path/to/info.xml -o output/path/sz input/path/xst.sz`
4. Updated file will be at the `-o path` you gave (or if you skip using `-o path`, it'll be written to input file_new.sz)
5. Try loading it in game, hopefully it'll load in fine

I did notice a couple XST files used slightly different (older?) headers than the others, not sure how repacking with this tool might affect them, if you have any issues let me know.

**Comment by thegreatprophetzarquon** [comment]
For me this gets to the "Reading XST..." and then after some time exits with "Out of memory."

**Comment by emoose** [comment]
Which file did you try with? Were you using it with the original compressed .sz?

**Comment by thegreatprophetzarquon** [comment]
Yep. Any of the ones in "Sprani," all with 2006 dates from the original PC C2C.  It gets pass the "Decompressing XST..." part just fine and then hangs on "Reading XST..." I checked my process list this time and it does indeed use up near all of my available memory, lol (I have 32 gb).

**Comment by emoose** [comment]
Moved to #90
