### ISSUE TITLE
OutRun 2 SP music loop points

### ISSUE THREAD

**Issue by lance8765** [emoose/OutRun2006Tweaks#8]
According to this page:

https://tcrf.net/OutRun_2006:_Coast_2_Coast_(PlayStation_2)/Version_Differences

"It also added loop points to many of the songs. In Coast 2 Coast, all songs would fade out and restart when they reached the end (most noticeable with the classic Outrun and Turbo OutRun music, where the fadeout point was shorter than a standard 5-stage race). The Japanese port addressed this, properly looping the 7 original Outrun 2 songs as well as the Outrun and Turbo Outrun music, but several others still fade out and restart during the longer 15-stage races."

Do you think it's possible to add something like that in the PC version?

ps: i have no idea which ones are part of the "several others" that still fade out and restart. :(

**Comment by emoose** [comment]
I /think/ we still need to add something to disable looping on the final stage though, otherwise I can't see how the end part of the song would get played?

Not sure how to check if we're on the final area yet, wonder how it was handled on PS2, did they disable looping at all there or did it just always loop?
