### ISSUE TITLE
[Bug]: Very Tiny Radio Textures on screen 

### ISSUE THREAD

**Issue by VirtualDavey** [emoose/OutRun2006Tweaks#89]
I can barely make it out but it appears to be textures from the radio (Perhaps others too). On all screens except actual race:
![DSC00466](https://github.com/user-attachments/assets/721aca2d-7f52-4470-8d74-6d19ba856d75)
![DSC00467](https://github.com/user-attachments/assets/285b87bb-4400-4abf-b02a-152704691b5d)
![DSC00468](https://github.com/user-attachments/assets/29b95f9c-28e9-46dd-a94e-bda5ccd71cdc)
![DSC00469](https://github.com/user-attachments/assets/17401b93-1b13-498e-a4af-bcc09b0a1362)

**Comment by emoose** [comment]
That might be the FXT overlay, the controls it shows there seem to be arcade ones from FXT anyway - maybe try running the game through OR2006C2C.exe instead of OR2FXT.exe, might also help with the Splash Wave issue you had too.

Did hear some had FXT working fine with tweaks, but really FXT never launched properly for me even with vanilla so I haven't been able to test with it... (if someone knows how to get them working together properly I'd be happy to update readme about it though)

**Comment by VirtualDavey** [comment]
When I used the  OR2006C2C.exe instead of OR2FXT.exe, your correct it solve the issues. But I also noticed that OR2FXT.exe worked properly if I opened FXTConfig.exe and and enabled "Force Menus to 4:3". Unfortunately, the entire game (menus and all) now only opens up in a window 1/9 or so the size of my monitor.

**Comment by Tenome** [comment]
Doesn't FXT use some weird bootleg overlay of images rather than actually replacing the textures? Maybe that caused it. They're not properly scaling.

**Comment by Sonic-TV** [comment]
> Doesn't FXT use some weird bootleg overlay of images rather than actually replacing the textures? Maybe that caused it. They're not properly scaling.

from the image they provided, yes.
It's better to add proper texture mode for 2SP.

**Comment by ArhumMK** [comment]
It would be better to play the game on a fresh install without FXT installed.
